<?php
declare(strict_types=1);
require __DIR__.'/config.php';
header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
function fail(string $message,int $status=400):never{http_response_code($status);echo json_encode(['error'=>$message]);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST')fail('Method not allowed.',405);
$raw=(string)file_get_contents('php://input');$timestamp=$_SERVER['HTTP_X_TIMESTAMP']??'';$signature=$_SERVER['HTTP_X_SIGNATURE']??'';$authorization=$_SERVER['HTTP_AUTHORIZATION']??'';
if(PORTFOLIO_BRIDGE_SECRET===''||!hash_equals('Bearer '.PORTFOLIO_BRIDGE_SECRET,$authorization))fail('Unauthorized.',401);
if(!ctype_digit($timestamp)||abs(time()-(int)$timestamp)>300)fail('Expired request.',401);
if(!hash_equals(hash_hmac('sha256',$timestamp.'.'.$raw,PORTFOLIO_BRIDGE_SECRET),$signature))fail('Invalid signature.',401);
$request=json_decode($raw,true);if(!is_array($request))fail('Invalid JSON.');$action=$request['action']??'';$payload=is_array($request['payload']??null)?$request['payload']:[];$db=portfolio_db();
$db->exec("CREATE TABLE IF NOT EXISTS klyvex_portfolio_blog_comments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,post_id BIGINT UNSIGNED NOT NULL,name VARCHAR(80) NOT NULL,email VARCHAR(190) NOT NULL,comment_text TEXT NOT NULL,status ENUM('pending','approved') NOT NULL DEFAULT 'pending',created_at DATETIME NOT NULL,INDEX idx_klyvex_blog_comments_post_status(post_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
try{
switch($action){
case'list_posts':$rows=$db->query("SELECT p.title,p.slug,p.excerpt,p.published_at,(SELECT COUNT(*) FROM klyvex_portfolio_likes l WHERE l.post_id=p.id) likes_count,(SELECT COUNT(*) FROM klyvex_portfolio_blog_comments c WHERE c.post_id=p.id AND c.status='approved') comments_count FROM klyvex_portfolio_posts p WHERE p.status='published' ORDER BY p.published_at DESC")->fetchAll();echo json_encode(['posts'=>$rows]);break;
case'get_post':$stmt=$db->prepare("SELECT p.id,p.title,p.slug,p.excerpt,p.content,p.published_at,(SELECT COUNT(*) FROM klyvex_portfolio_likes l WHERE l.post_id=p.id) likes_count FROM klyvex_portfolio_posts p WHERE p.slug=? AND p.status='published' LIMIT 1");$stmt->execute([(string)($payload['slug']??'')]);$post=$stmt->fetch()?:null;$comments=[];$enabled=($db->query("SELECT setting_value FROM klyvex_portfolio_settings WHERE setting_key='comments_enabled'")->fetchColumn()?:'1')==='1';if($post){$paragraphs=preg_split('/\R{2,}/',trim($post['content']))?:[];$post['content_html']=implode('',array_map(fn($p)=>'<p>'.nl2br(htmlspecialchars(trim($p),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')).'</p>',$paragraphs));unset($post['content']);$stmt=$db->prepare("SELECT name,comment_text AS comment,created_at FROM klyvex_portfolio_blog_comments WHERE post_id=? AND status='approved' ORDER BY created_at DESC");$stmt->execute([$post['id']]);$comments=$stmt->fetchAll();unset($post['id']);}echo json_encode(['post'=>$post,'comments'=>$comments,'comments_enabled'=>$enabled]);break;
case'like_post':$stmt=$db->prepare("SELECT id FROM klyvex_portfolio_posts WHERE slug=? AND status='published'");$stmt->execute([(string)($payload['slug']??'')]);$postId=(int)$stmt->fetchColumn();if(!$postId)fail('Post not found.',404);$stmt=$db->prepare('INSERT IGNORE INTO klyvex_portfolio_likes(post_id,visitor_hash,created_at) VALUES(?,?,UTC_TIMESTAMP())');$stmt->execute([$postId,(string)($payload['visitor']??'')]);$stmt=$db->prepare('SELECT COUNT(*) FROM klyvex_portfolio_likes WHERE post_id=?');$stmt->execute([$postId]);echo json_encode(['likes_count'=>(int)$stmt->fetchColumn()]);break;
case'submit_comment':$enabled=($db->query("SELECT setting_value FROM klyvex_portfolio_settings WHERE setting_key='comments_enabled'")->fetchColumn()?:'1')==='1';if(!$enabled)fail('Comments are currently closed.',403);$stmt=$db->prepare("SELECT id FROM klyvex_portfolio_posts WHERE slug=? AND status='published'");$stmt->execute([(string)($payload['slug']??'')]);$postId=(int)$stmt->fetchColumn();if(!$postId)fail('Post not found.',404);$stmt=$db->prepare("INSERT INTO klyvex_portfolio_blog_comments(post_id,name,email,comment_text,status,created_at) VALUES(?,?,?,?, 'pending',UTC_TIMESTAMP())");$stmt->execute([$postId,(string)$payload['name'],(string)$payload['email'],(string)$payload['comment']]);echo json_encode(['message'=>'Comment submitted for moderation.']);break;
case'admin_list_posts':echo json_encode(['posts'=>$db->query('SELECT * FROM klyvex_portfolio_posts ORDER BY updated_at DESC')->fetchAll()]);break;
case'admin_comments':$rows=$db->query('SELECT * FROM klyvex_portfolio_blog_comments')->fetchAll();$title=$db->prepare('SELECT title FROM klyvex_portfolio_posts WHERE id=? LIMIT 1');foreach($rows as &$row){$row['comment']=$row['comment_text']??'';$title->execute([(int)($row['post_id']??0)]);$row['post_title']=$title->fetchColumn()?:'Unknown post';}unset($row);$enabled=($db->query("SELECT setting_value FROM klyvex_portfolio_settings WHERE setting_key='comments_enabled'")->fetchColumn()?:'1')==='1';echo json_encode(['comments'=>array_reverse($rows),'comments_enabled'=>$enabled]);break;
case'moderate_comment':$status=($payload['status']??'')==='approved'?'approved':'pending';$stmt=$db->prepare('UPDATE klyvex_portfolio_blog_comments SET status=? WHERE id=?');$stmt->execute([$status,(int)$payload['id']]);echo json_encode(['saved'=>true]);break;
case'delete_comment':$stmt=$db->prepare('DELETE FROM klyvex_portfolio_blog_comments WHERE id=?');$stmt->execute([(int)$payload['id']]);echo json_encode(['deleted'=>true]);break;
case'save_settings':$value=!empty($payload['comments_enabled'])?'1':'0';$stmt=$db->prepare("INSERT INTO klyvex_portfolio_settings(setting_key,setting_value,updated_at) VALUES('comments_enabled',?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),updated_at=UTC_TIMESTAMP()");$stmt->execute([$value]);echo json_encode(['comments_enabled'=>$value==='1']);break;
case'save_post':$title=trim((string)($payload['title']??''));$slug=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','-',(string)(($payload['slug']??'')?:$title)),'-'));$excerpt=trim((string)($payload['excerpt']??''));$content=trim((string)($payload['content']??''));$status=($payload['status']??'')==='published'?'published':'draft';if($title===''||$slug===''||$excerpt===''||$content==='')fail('Complete all post fields.',422);$id=(int)($payload['id']??0);if($id){$stmt=$db->prepare("UPDATE klyvex_portfolio_posts SET title=?,slug=?,excerpt=?,content=?,status=?,published_at=IF(?='published' AND published_at IS NULL,UTC_TIMESTAMP(),published_at),updated_at=UTC_TIMESTAMP() WHERE id=?");$stmt->execute([$title,$slug,$excerpt,$content,$status,$status,$id]);}else{$stmt=$db->prepare("INSERT INTO klyvex_portfolio_posts(title,slug,excerpt,content,status,published_at,created_at,updated_at) VALUES(?,?,?,?,?,IF(?='published',UTC_TIMESTAMP(),NULL),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$stmt->execute([$title,$slug,$excerpt,$content,$status,$status]);}echo json_encode(['saved'=>true]);break;
case'delete_post':$id=(int)($payload['id']??0);$db->prepare('DELETE FROM klyvex_portfolio_blog_comments WHERE post_id=?')->execute([$id]);$db->prepare('DELETE FROM klyvex_portfolio_likes WHERE post_id=?')->execute([$id]);$db->prepare('DELETE FROM klyvex_portfolio_posts WHERE id=?')->execute([$id]);echo json_encode(['deleted'=>true]);break;
default:fail('Unknown action.',404);
}
}catch(PDOException $error){error_log('Portfolio bridge database error: '.$error->getMessage());fail('Database operation failed.',500);}
